// Generated by FlutterFire CLI.
// Run: flutterfire configure --project=<your-firebase-project-id>
// See: https://firebase.flutter.dev/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project values after running:
  //   flutterfire configure --project=<your-firebase-project-id>
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzjADR_pFG58VCiQvXqfAt_MuawaLo30',
    appId: '1:566889660924:android:ccbfd440c75b709aae3279',
    messagingSenderId: '566889660924',
    projectId: 'swades-hackathon-aa7eb',
    storageBucket: 'swades-hackathon-aa7eb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHP4xeemffBspgIbUetZWvL2hg-fnSZoI',
    appId: '1:566889660924:ios:cc9b9ad1cabda616ae3279',
    messagingSenderId: '566889660924',
    projectId: 'swades-hackathon-aa7eb',
    storageBucket: 'swades-hackathon-aa7eb.firebasestorage.app',
    androidClientId: '566889660924-1fo895krs7oihneaf31dp5j02pfiui3m.apps.googleusercontent.com',
    iosClientId: '566889660924-puadm4vt041t5mbcd0imd282gpm55e6d.apps.googleusercontent.com',
    iosBundleId: 'com.quickslot.quickslot',
  );
}
